networks:
  webapp:
    name: webapp
    external: true

services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn build && yarn start"
    ports:
      - 4000:4000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: wfh
    networks:
      - webapp
  
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: wfh
    networks:
      - webapp
      
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis:/var/lib/redis/data
  #   networks:
  #     - webapp
  # nginx:
  #   image: nginx:1.23.4-alpine
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./:/usr/share/nginx/html
  #   depends_on:
  #     - app
volumes:
  postgres: # redis:
