export const data = [
  {
    email: 'john.doe@example.com',
    password: 'd0eP@ssw0rd!',
    firstName: 'John',
    lastName: 'Doe',
    country: 'United States',
  },
  {
    email: 'jane.doe@example.com',
    password: 'd0eP@ssw0rd!',
    firstName: 'Jane',
    lastName: 'Doe',
    country: 'Canada',
  },
  {
    email: 'adam.smith@example.com',
    password: 'sM1thP@ssw0rd!',
    firstName: 'Adam',
    lastName: 'Smith',
    country: 'United Kingdom',
  },
  {
    email: 'eva.jones@example.com',
    password: 'j0nesP@ssw0rd!',
    firstName: 'Eva',
    lastName: 'Jones',
    country: 'Australia',
  },
  {
    email: 'peter.chan@example.com',
    password: 'cH@nP@ssw0rd!',
    firstName: 'Peter',
    lastName: 'Chan',
    country: 'Hong Kong',
  },
  {
    email: 'maria.garcia@example.com',
    password: 'g@rc1aP@ssw0rd!',
    firstName: 'Maria',
    lastName: 'Garcia',
    country: 'Spain',
  },
  {
    email: 'lee.kim@example.com',
    password: 'k1mP@ssw0rd!',
    firstName: 'Lee',
    lastName: 'Kim',
    country: 'South Korea',
  },
  {
    email: 'olivia.wang@example.com',
    password: 'w@ngP@ssw0rd!',
    firstName: 'Olivia',
    lastName: 'Wang',
    country: 'China',
  },
  {
    email: 'michael.smith@example.com',
    password: 'sM1thP@ssw0rd!',
    firstName: 'Michael',
    lastName: 'Smith',
    country: 'United States',
  },
  {
    email: 'jessica.nguyen@example.com',
    password: 'nguy3nP@ssw0rd!',
    firstName: 'Jessica',
    lastName: 'Nguyen',
    country: 'Vietnam',
  },
];
